-- Dawenli database schema entry point
--
-- The canonical schema is maintained as an idempotent migration. Apply it
-- with `supabase db push` or execute this file from the migration directory:
--   supabase/migrations/202609240001_harden_dawenli.sql
--
-- Keeping this pointer avoids two divergent schemas and preserves the path
-- used by existing documentation and deployment checks.
