import { WorshipPreferences } from './WorshipPreferences';
import { sortWorshipDefinitions, worshipSections } from '../../utils/worshipLayout';
import React, { useCallback, useEffect, useMemo, useRef, useState } from 'react';
import { Check, CalendarDays, Moon, Plus, Sparkles } from 'lucide-react';
import type { Pillar, ProgressionPath, QuranHifzTracker, QuranKhatma, SleepSchedule, WorshipDefinition, WorshipLog } from '../../types/hierarchical';
import { toLocalDateKey } from '../../utils/date';
import { hijriDate, isEditableWorshipDate, isWhiteDay, isWorshipScheduled, configuredProgression, targetStreak, updateWorshipLog, worshipInsights, worshipStreak, worshipSummary, QURAN_QUARTER_PAGES, QURAN_QUARTERS_PER_JUZ } from '../../utils/ibadat';
import { analyzeWorshipInsight } from '../../utils/speechRecognition';
import type { PushNotificationPreferences } from '../../utils/pushNotifications';
import { getPushPreferences } from '../../utils/pushNotifications';

type Props = {
  pillars: Pillar[]; definitions: WorshipDefinition[]; logs: WorshipLog[];
  onUpdateDefinition: (id: string, patch: Partial<WorshipDefinition>) => void;
  onSetup: (categories: WorshipDefinition['category'][]) => void;
  onSaveLog: (log: WorshipLog) => void;
  onOpenTimeBlocking: () => void; onSuggestTimeBlocks: () => void;
  progressionPaths: ProgressionPath[]; onApproveProgression: (pathId: string) => void;
  khatmas: QuranKhatma[]; onUpdateKhatma: (id: string, page: number) => void;
  sleepSchedules: SleepSchedule[]; onUpdateSleep: (id: string, changes: Partial<SleepSchedule>) => void;
  onEnableNotifications: (preferences: PushNotificationPreferences) => void;
  hifzTrackers: QuranHifzTracker[]; onUpdateHifz: (id: string, pages: number) => void;
};

const choices: Array<{ category: WorshipDefinition['category']; label: string }> = [
  { category: 'salah', label: 'الصلوات الخمس' }, { category: 'sunnah_rawatib', label: 'السنن الرواتب' }, { category: 'adhkar', label: 'أذكار الصباح والمساء' },
  { category: 'quran_wird', label: 'ورد القرآن والختمة' }, { category: 'qiyam', label: 'قيام الليل' },
  { category: 'fasting', label: 'صيام التطوع' }, { category: 'sadaqah', label: 'الصدقة' },
  { category: 'custom_dua', label: 'أوراد وأدعية مخصصة' }, { category: 'quran_hifz', label: 'حفظ القرآن ومراجعته' },
];

export const IbadatDashboard: React.FC<Props> = ({ onUpdateDefinition, pillars, definitions, logs, onSetup, onSaveLog, onOpenTimeBlocking, onSuggestTimeBlocks, progressionPaths, onApproveProgression, khatmas, onUpdateKhatma, sleepSchedules, onUpdateSleep, onEnableNotifications, hifzTrackers, onUpdateHifz }) => {
  const [selected, setSelected] = useState(choices.slice(0, 4).map((item) => item.category));
  const [showSetup, setShowSetup] = useState(false);
  const [date, setDate] = useState(toLocalDateKey());
  const [aiInsight, setAiInsight] = useState<{ summary: string; suggestions: string[] } | null>(null);
  const [isAnalyzing, setIsAnalyzing] = useState(false);
  const [notificationPreferences, setNotificationPreferences] = useState({ prayerEnabled: true, taskEnabled: true, worshipEnabled: true, adhkarEnabled: true, quranEnabled: true, qiyamEnabled: true, sleepEnabled: true, streakEnabled: true });
  const [notificationLoading, setNotificationLoading] = useState(true);
  const [notificationError, setNotificationError] = useState('');
  const notificationRequestRef = useRef(0);
  const loadNotificationPreferences = useCallback(async () => {
    const requestId = ++notificationRequestRef.current;
    setNotificationLoading(true);
    setNotificationError('');
    try {
      const saved = await getPushPreferences();
      if (requestId === notificationRequestRef.current && saved) {
        setNotificationPreferences((current) => ({ ...current, ...saved }));
      }
    } catch (error) {
      if (requestId === notificationRequestRef.current) {
        setNotificationError(error instanceof Error ? error.message : 'تعذر تحميل الإعدادات');
      }
    } finally {
      if (requestId === notificationRequestRef.current) setNotificationLoading(false);
    }
  }, []);
  useEffect(() => {
    void loadNotificationPreferences();
    return () => { notificationRequestRef.current += 1; };
  }, [loadNotificationPreferences]);
  const today = toLocalDateKey();
  const dayDefinitions = definitions.filter((item) => item.is_active && (item.frequency === 'daily' || item.frequency === 'custom'));
  const summary = useMemo(() => worshipSummary(definitions, logs, date), [definitions, logs, date]);
  const hijri = hijriDate(new Date(`${date}T12:00:00`));
  if (!definitions.length || showSetup) return <section className="max-w-3xl mx-auto overflow-hidden rounded-3xl border border-emerald-100 bg-white shadow-sm dark:border-emerald-900/70 dark:bg-slate-900">
    <div className="bg-linear-to-br from-emerald-950 via-emerald-900 to-teal-800 p-7 text-white sm:p-10"><Moon className="mb-5 h-12 w-12 text-emerald-200" /><p className="mb-2 text-xs font-bold tracking-[0.2em] text-emerald-200">خطوتك الهادئة نحو الثبات</p><h1 className="text-2xl font-black sm:text-3xl">ابدأ منظومة عباداتك</h1><p className="mt-3 max-w-xl text-sm leading-7 text-emerald-50/85">اختر ما يناسبك الآن. سننشئ ركيزة «العلاقة مع الله» ونربط بها اختياراتك دون ازدحام أو بيانات افتراضية.</p></div>
    <div className="space-y-5 p-5 sm:p-8">{definitions.length > 0 && <button type="button" onClick={() => setShowSetup(false)} className="rounded-xl border px-4 py-2">رجوع دون تغيير</button>}<div className="grid grid-cols-1 gap-3 text-right sm:grid-cols-2">{choices.map(({ category, label }) => <label key={category} className={`flex min-w-0 cursor-pointer items-center gap-3 rounded-2xl border p-4 transition-colors dark:border-slate-700 ${selected.includes(category) ? 'border-emerald-400 bg-emerald-50 dark:border-emerald-700 dark:bg-emerald-950/30' : 'border-slate-200 hover:bg-slate-50 dark:hover:bg-slate-800/70'}`}><input className="h-4 w-4 accent-emerald-700" type="checkbox" aria-label={`اختيار ${label}`} checked={selected.includes(category)} onChange={() => setSelected((old) => old.includes(category) ? old.filter((x) => x !== category) : [...old, category])} />{label}</label>)}</div>
    <button type="button" disabled={!selected.length} onClick={() => { onSetup(selected); setShowSetup(false); }} className="w-full rounded-2xl bg-emerald-700 px-5 py-3.5 font-bold text-white shadow-sm transition hover:bg-emerald-800 disabled:cursor-not-allowed disabled:opacity-50">تفعيل العبادات المختارة ({selected.length})</button></div>
  </section>;
  const save = (definition: WorshipDefinition, patch: Partial<WorshipLog>) => {
    if (!isEditableWorshipDate(date)) return;
    const prior = logs.find((log) => log.worship_id === definition.id && log.date === date);
    onSaveLog(updateWorshipLog(definition, date, prior, patch));
  };
  const streak = worshipStreak(definitions, logs);
  const requestAiInsight = async () => {
    setIsAnalyzing(true);
    try { setAiInsight(await analyzeWorshipInsight({ completionRate: summary.rate, completed: summary.completed, total: summary.total, streak, date })); }
    catch { setAiInsight({ summary: 'تعذر الاتصال بتحليل Gemini. تأكد من حفظ مفتاح Gemini للحساب.', suggestions: [] }); }
    finally { setIsAnalyzing(false); }
  };
  return <section className="min-w-0 space-y-5 pb-8">
    <button type="button" onClick={() => setShowSetup(true)} className="rounded-xl border px-4 py-3 text-sm dark:border-slate-700">إضافة عبادات ومسارات تدرّج — دون حذف السجلات الحالية</button>
    <div className="flex flex-wrap items-center justify-between gap-3"><div><h1 className="text-2xl font-black">🕌 العبادات والأوراد</h1><p className="text-sm text-slate-500">مرتبطة بركيزة {pillars.find((p) => p.id === definitions[0].pillar_id)?.title || 'العلاقة مع الله'}</p></div><div className="flex flex-wrap items-center gap-2"><div className="flex max-w-full flex-wrap items-center gap-2 rounded-xl border px-3 py-2 text-xs dark:border-slate-700" role="group" aria-label="إعدادات أنواع الإشعارات">{([['prayerEnabled','الصلاة'],['taskEnabled','المهام'],['adhkarEnabled','الأذكار'],['quranEnabled','القرآن'],['qiyamEnabled','قيام الليل'],['sleepEnabled','النوم'],['streakEnabled','الستريك']] as const).map(([key, label]) => <label key={key} className="inline-flex items-center gap-1"><input type="checkbox" aria-label={`تفعيل إشعارات ${label}`} disabled={notificationLoading} checked={notificationPreferences[key]} onChange={(e) => setNotificationPreferences((old) => ({ ...old, [key]: e.target.checked }))} /> {label}</label>)}</div><button type="button" disabled={notificationLoading} onClick={() => onEnableNotifications(notificationPreferences)} className="rounded-xl border px-3 py-2 text-sm dark:border-slate-700">حفظ إعدادات التذكيرات</button>{notificationError && <p role="alert" className="text-sm text-red-600">{notificationError}<button type="button" onClick={() => void loadNotificationPreferences()} className="mr-2 underline">إعادة المحاولة</button></p>}<button type="button" onClick={onSuggestTimeBlocks} className="rounded-xl bg-emerald-700 text-white px-3 py-2 text-sm">إضافة الكتل المقترحة</button><button type="button" onClick={onOpenTimeBlocking} className="rounded-xl border px-3 py-2 text-sm dark:border-slate-700">حجب الوقت</button></div></div>
    <div className="grid grid-cols-2 gap-3 sm:grid-cols-4"><Stat label="التزام اليوم" value={`${summary.rate}%`} /><Stat label="المكتمل" value={`${summary.completed}/${summary.total}`} /><Stat label="الستريك" value={`${streak} يوم`} /><Stat label="التاريخ" value={date} /></div>
    <div className="rounded-2xl border border-emerald-100 bg-white p-4 shadow-sm dark:border-slate-800 dark:bg-slate-900"><div className="mb-2 flex items-center justify-between gap-3 text-xs"><span className="font-bold text-slate-700 dark:text-slate-200">تقدّم اليوم</span><span className="font-black text-emerald-700 dark:text-emerald-300">{summary.rate}%</span></div><div className="h-2 overflow-hidden rounded-full bg-slate-100 dark:bg-slate-800"><div className="h-full rounded-full bg-linear-to-l from-emerald-600 to-teal-400 transition-all" style={{ width: `${summary.rate}%` }} /></div></div>
    <aside className="rounded-2xl border border-amber-200 dark:border-amber-900 bg-amber-50 dark:bg-amber-950/30 p-4"><p className="font-bold text-sm">✨ ملخص التزامك</p><ul className="mt-2 space-y-1 text-sm text-slate-700 dark:text-slate-200">{worshipInsights(definitions, logs, date).map((insight) => <li key={insight}>• {insight}</li>)}</ul></aside>
    <aside className="rounded-2xl border border-violet-200 dark:border-violet-900 bg-violet-50 dark:bg-violet-950/30 p-4"><div className="flex items-center justify-between gap-3"><p className="font-bold text-sm">✨ تحليل Gemini الاختياري</p><button type="button" disabled={isAnalyzing} onClick={() => void requestAiInsight()} className="rounded-lg bg-violet-700 text-white px-3 py-2 text-xs disabled:opacity-50">{isAnalyzing ? 'جاري التحليل…' : 'حلل التزامي'}</button></div>{aiInsight && <div className="mt-3 text-sm"><p>{aiInsight.summary}</p>{aiInsight.suggestions.map((item) => <p key={item} className="mt-1 text-slate-600 dark:text-slate-300">• {item}</p>)}</div>}</aside>
    <div className="flex flex-wrap items-center gap-3 rounded-2xl border border-slate-200 bg-white p-3 shadow-sm dark:border-slate-800 dark:bg-slate-900"><CalendarDays className="h-4 w-4 text-emerald-700 dark:text-emerald-300" /><label className="text-sm font-bold" htmlFor="worship-date">تسجيل يوم</label><input id="worship-date" aria-label="تاريخ سجل العبادة" type="date" value={date} max={today} onChange={(e) => { if (e.target.value) setDate(e.target.value); }} className="min-w-0 rounded-xl border border-slate-200 bg-transparent p-2 text-sm dark:border-slate-700 dark:bg-slate-800" /><span className="text-xs text-slate-500">{hijri.label}{isWhiteDay(new Date(`${date}T12:00:00`)) ? ' · من الأيام البيض' : ''}</span>{!isEditableWorshipDate(date) && <span className="text-xs text-rose-600">التعديل متاح لآخر 30 يومًا فقط</span>}</div>
    <nav aria-label="أقسام العبادات" className="flex flex-wrap gap-2">{worshipSections.filter((section) => dayDefinitions.some((d) => d.category === section.category)).map((section) => <a key={section.category} href={`#worship-${section.category}`} className="rounded-xl border px-3 py-2 text-sm dark:border-slate-700">{section.title}</a>)}</nav>
    {worshipSections.map((section) => { const items = sortWorshipDefinitions(dayDefinitions.filter((d) => d.category === section.category)); if (!items.length) return null; return <section id={`worship-${section.category}`} key={section.category} className="scroll-mt-20 space-y-3" aria-label={section.title}><div className="border-b border-slate-200 pb-3 dark:border-slate-700"><h2 className="text-xl font-black">{section.title}</h2><p className="mt-1 text-sm text-slate-500 dark:text-slate-400">{section.description}</p></div><div className="grid min-w-0 grid-cols-1 gap-4 lg:grid-cols-2">{items.map((definition) => { const log = logs.find((item) => item.worship_id === definition.id && item.date === date); return <article key={definition.id} className="min-w-0 space-y-4 rounded-3xl border border-slate-200 bg-white p-5 shadow-sm transition-shadow hover:shadow-md dark:border-slate-800 dark:bg-slate-900"><div className="flex min-w-0 items-start justify-between gap-3"><h2 className="min-w-0 truncate text-base font-black">{definition.category === 'salah' ? '🕌' : definition.category === 'quran_wird' ? '📖' : '📿'} {definition.title}</h2><button type="button" aria-label={`تسجيل ${definition.title}`} disabled={!isEditableWorshipDate(date)} onClick={() => save(definition, { is_completed: !log?.is_completed })} className={`shrink-0 rounded-xl px-3 py-2 text-sm font-bold transition ${log?.is_completed ? 'bg-emerald-100 text-emerald-800 dark:bg-emerald-950 dark:text-emerald-300' : 'bg-slate-100 dark:bg-slate-800 dark:text-slate-200'}`}><Check className="inline h-4 w-4" /> {log?.is_completed ? 'تم' : 'تسجيل'}</button></div>
      <WorshipPreferences key={definition.id + (definition.updated_at || '')} definition={definition} onSave={onUpdateDefinition} />
      {!isWorshipScheduled(definition, date) && <p className="text-xs text-slate-500">غير مقرر في هذا اليوم — لا يخفض تقييمك.</p>}
      {definition.category === 'salah' && <div className="flex flex-wrap gap-2"><select aria-label={`أداء ${definition.title}`} value={log?.performance || ''} onChange={(e) => save(definition, { performance: e.target.value as WorshipLog['performance'], is_completed: e.target.value === 'ada' || e.target.value === 'qada' })} className="min-h-11 max-w-full rounded-xl border border-emerald-200 bg-emerald-50 px-3 py-2 text-sm font-semibold text-emerald-950 shadow-sm focus:ring-2 focus:ring-emerald-500 dark:border-slate-600 dark:bg-slate-800 dark:text-emerald-100"><option value="">نوع الأداء</option><option value="ada">أداء</option><option value="qada">قضاء</option><option value="missed">فاتت</option></select><select aria-label={`جماعة ${definition.title}`} value={log?.congregation || ''} onChange={(e) => save(definition, { congregation: e.target.value ? e.target.value as WorshipLog['congregation'] : null })} className="min-h-11 max-w-full rounded-xl border border-emerald-200 bg-emerald-50 px-3 py-2 text-sm font-semibold text-emerald-950 shadow-sm focus:ring-2 focus:ring-emerald-500 dark:border-slate-600 dark:bg-slate-800 dark:text-emerald-100"><option value="">جماعة / فرد</option><option value="jamaah">جماعة</option><option value="fard">فرد</option></select></div>}
      {definition.tracking_type === 'counter' && <div className="flex items-center gap-3"><button aria-label={`زيادة ${definition.title}`} onClick={() => save(definition, { count: (log?.count || 0) + 1, is_completed: (log?.count || 0) + 1 >= (definition.target_count || 1) })} className="rounded-full bg-emerald-700 text-white w-10 h-10"><Plus className="w-5 h-5 mx-auto" /></button><button type="button" aria-label={`تقليل ${definition.title}`} disabled={!log?.count || !isEditableWorshipDate(date)} onClick={() => { const count = Math.max(0, (log?.count || 0) - 1); save(definition, { count, is_completed: count >= (definition.target_count || 1) }); }} className="h-10 w-10 rounded-full border dark:border-slate-600 disabled:opacity-40">−</button><span>{log?.count || 0}/{definition.target_count || '—'}</span></div>}
      {definition.tracking_type === 'pages' && <label className="block space-y-2 text-sm"><span className="block text-slate-600 dark:text-slate-300">{definition.category === 'quran_wird' ? `أرباع الحزب المقروءة · الهدف: ${Math.max(1, Math.ceil((definition.target_pages || QURAN_QUARTER_PAGES) / QURAN_QUARTER_PAGES))} يوميًا · الجزء = ${QURAN_QUARTERS_PER_JUZ} أرباع` : `الصفحات المقروءة · الهدف: ${definition.target_pages || 1}`}</span><input aria-label={`${definition.category === 'quran_wird' ? 'أرباع' : 'صفحات'} ${definition.title}`} type="number" min="0" step="1" value={log?.pages_read ? log.pages_read / (definition.category === 'quran_wird' ? QURAN_QUARTER_PAGES : 1) : ''} onChange={(e) => { const pages = Number(e.target.value) * (definition.category === 'quran_wird' ? QURAN_QUARTER_PAGES : 1); const goal = definition.category === 'quran_wird' ? Math.max(QURAN_QUARTER_PAGES, definition.target_pages || QURAN_QUARTER_PAGES) : (definition.target_pages || 1); save(definition, { pages_read: pages, is_completed: pages >= goal }); }} className="w-28 rounded-lg border p-2 dark:bg-slate-800 dark:border-slate-700" /></label>}
      {definition.tracking_type === 'amount' && <input aria-label={`مبلغ ${definition.title}`} type="number" min="0" placeholder="مبلغ اختياري خاص" value={log?.amount || ''} onChange={(e) => save(definition, { amount: Number(e.target.value) || null })} className="w-44 rounded-lg border p-2 text-sm dark:bg-slate-800 dark:border-slate-700" />}
      {definition.category === 'qiyam' && <div className="flex flex-wrap gap-2"><input aria-label="عدد ركعات قيام الليل" type="number" min="1" placeholder="الركعات" value={log?.rakaat_count || ''} onChange={(e) => save(definition, { rakaat_count: Number(e.target.value) || null, is_completed: Number(e.target.value) >= (definition.target_count || 2) })} className="w-28 rounded-lg border p-2 dark:bg-slate-800 dark:border-slate-700" /><input aria-label="وقت قيام الليل" type="time" value={log?.performed_at_time || ''} onChange={(e) => save(definition, { performed_at_time: e.target.value || null })} className="rounded-lg border p-2 dark:bg-slate-800 dark:border-slate-700" /></div>}
      {definition.category === 'fasting' && <select aria-label="نوع صيام التطوع" value={log?.fasting_type || ''} onChange={(e) => save(definition, { fasting_type: e.target.value as WorshipLog['fasting_type'] })} className="min-h-11 max-w-full rounded-xl border border-emerald-200 bg-emerald-50 px-3 py-2 text-sm font-semibold text-emerald-950 shadow-sm focus:ring-2 focus:ring-emerald-500 dark:border-slate-600 dark:bg-slate-800 dark:text-emerald-100"><option value="">نوع الصيام</option><option value="monday_thursday">الاثنين والخميس</option><option value="white_days">الأيام البيض</option><option value="dawood">صيام داود</option><option value="ramadan">رمضان</option><option value="other">آخر</option></select>}
    </article>; })}</div></section>; })}
    {progressionPaths.map((storedPath) => { const definition = definitions.find((d) => d.id === storedPath.worship_id); const path = definition ? configuredProgression(storedPath, definition) : storedPath; const completed = definition ? targetStreak(definition, logs, path.stage_start_date) : 0; const next = path.stages[path.current_stage_index + 1]; const suggestion = next && completed >= (path.stages[path.current_stage_index]?.days_required || 30) ? `هل تريد الانتقال إلى ${next.title}؟` : null; const stage = path.stages[path.current_stage_index]; return <article key={path.id} className="rounded-2xl border border-amber-200 bg-amber-50 dark:bg-amber-950/30 dark:border-amber-900 p-4"><h2 className="font-bold">✨ {path.title}: {stage?.title}</h2><p className="text-sm mt-2">{stage?.description}</p><p className="text-sm mt-1">الأيام المنجزة في المرحلة: {completed}/{stage?.days_required || '—'}</p>{suggestion ? <button type="button" onClick={() => onApproveProgression(path.id)} className="mt-3 rounded-lg bg-amber-600 text-white px-3 py-2 text-sm">{suggestion}</button> : <p className="text-xs text-slate-500 mt-2">التدرج اقتراحي فقط؛ لن تتغير مرحلتك تلقائيًا.</p>}</article>})}
    {khatmas.map((khatma) => <article key={khatma.id} className="rounded-2xl border bg-white dark:bg-slate-900 dark:border-slate-800 p-4"><h2 className="font-bold">📖 الختمة #{khatma.khatma_number}</h2><p className="text-sm mt-1">صفحة {khatma.current_page}/604 · جزء {khatma.current_juz}</p><input aria-label="الصفحة الحالية للختمة" type="range" min="1" max="604" value={khatma.current_page} onChange={(e) => onUpdateKhatma(khatma.id, Number(e.target.value))} className="w-full accent-emerald-700 mt-3" /></article>)}
    {sleepSchedules.map((schedule) => <article key={schedule.id} className="rounded-2xl border bg-indigo-50 dark:bg-indigo-950/30 dark:border-indigo-900 p-4 space-y-2"><h2 className="font-bold">😴 جدول النوم التدريجي</h2><p className="text-sm">هدفك: النوم {schedule.ultimate_bedtime} والاستيقاظ {schedule.ultimate_waketime}</p><div className="flex flex-wrap gap-2"><label className="text-xs">الحالي <input aria-label="وقت النوم الحالي" type="time" value={schedule.current_bedtime} onChange={(e) => onUpdateSleep(schedule.id, { current_bedtime: e.target.value })} className="mr-1 rounded border p-1 dark:bg-slate-800" /></label><label className="text-xs">الاستيقاظ <input aria-label="وقت الاستيقاظ الحالي" type="time" value={schedule.current_waketime} onChange={(e) => onUpdateSleep(schedule.id, { current_waketime: e.target.value })} className="mr-1 rounded border p-1 dark:bg-slate-800" /></label></div><p className="text-xs text-slate-500">اقتراح تدريجي: قدّم وقت النوم {schedule.adjustment_minutes} دقيقة كل {schedule.adjustment_frequency_days} أيام بعد اعتمادك.</p></article>)}
    {hifzTrackers.map((tracker) => <article key={tracker.id} className="rounded-2xl border bg-white dark:bg-slate-900 dark:border-slate-800 p-4"><h2 className="font-bold">📗 حفظ القرآن ومراجعته</h2><p className="text-sm mt-1">الصفحات المحفوظة: {tracker.total_memorized_pages}/604 · مراجعة يومية: {tracker.daily_review_pages} صفحة</p><input aria-label="إجمالي صفحات الحفظ" type="number" min="0" max="604" value={tracker.total_memorized_pages} onChange={(e) => onUpdateHifz(tracker.id, Number(e.target.value))} className="mt-3 w-28 rounded-lg border p-2 dark:bg-slate-800 dark:border-slate-700" /></article>)}
    <p className="text-xs text-slate-500 flex gap-1 items-center"><Sparkles className="w-3 h-3" />الذكاء الاصطناعي يعرض تحليلات وتشجيعًا فقط، ولا يصدر أحكامًا أو فتاوى.</p>
  </section>;
};
const Stat = ({ label, value }: { label: string; value: string }) => <div className="rounded-2xl border border-emerald-100 bg-emerald-50/80 p-4 shadow-sm dark:border-emerald-900/60 dark:bg-emerald-950/35"><p className="text-xs font-medium text-slate-500 dark:text-slate-400">{label}</p><p className="mt-1 text-lg font-black text-emerald-950 dark:text-emerald-100">{value}</p></div>;
